### ISSUE TITLE
Revise the Research Motivation and update the READ.ME file

### ISSUE THREAD

**Issue by RebeccaKeijzer** [course-dprep/team-project-dprep_group6#10]
Hi,

After reviewing the research statement we've posted, there is room for improvement. The research question could be more clearly articulated. 

**Deliverables:**
- Update the READ.ME file with the final statements, indicating clearly the festivals, dates and cities in the scope of the analysis.

**Comment by catarinalsferreira** [comment]
Hi all, 
I updated our the motivation and the questions we want to answer with this research.
The issue can be closed.
