### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by RebeccaKeijzer** [course-dprep/team-project-dprep_group6#11]
**The readme.md file is created but needs to be adapted. **

Check one of the workflow templates available at [Tilburg Science Hub](https://tilburgsciencehub.com/examples/simple-reproducible-workflow/). 
This repository contains a readme.md (in markdown format, so that it renders well on GitHub), which clearly explains the project’s goal, and provides instructions to potential contributors/replicators on how to run the project. 

Tip: Structure your README.md

**Deliverables:**
- formulate the method of research and the reason why you are using regression analysis.
-  describe the variables used.

**Comment by catarinalsferreira** [comment]
This issue is done. 

Catarina
